openapi: 3.2.0
info:
  description: Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: 'Akamai: Linode Managed Linode settings API'
  version: 4.229.1
servers:
- url: https://api.linode.com
tags:
- description: View and update settings related to Linode Managed for each of your Linodes.
  name: Managed Linode settings
paths:
  /{apiVersion}/managed/linode-settings:
    parameters:
    - description: __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
      example: '{{apiVersion}}'
      in: path
      name: apiVersion
      required: true
      schema:
        enum:
        - v4
        - v4beta
        example: v4
        type: string
      x-akamai:
        file-path: parameters/api-version-path.yaml
    x-akamai:
      file-path: paths/managed-linode-settings.yaml
      path-info: /{apiVersion}/managed/linode-settings
    x-linode-cli-command: managed
    get:
      description: 'Returns a paginated list of managed settings for your Linodes (one entry per Linode).


        This operation can only be accessed by the unrestricted users of an account.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_only`


        **CLI**


        ```shell

        linode-cli managed linode-settings-list

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/get-managed-linode-settings
      operationId: get-managed-linode-settings
      parameters:
      - description: The page of a collection to return.
        example: '{{page}}'
        in: query
        name: page
        required: false
        schema:
          default: 1
          example: 6
          minimum: 1
          type: integer
        x-akamai:
          file-path: parameters/page-offset.yaml
      - description: The number of items to return per page.
        example: '{{page_size}}'
        in: query
        name: page_size
        schema:
          default: 100
          example: 50
          maximum: 500
          minimum: 25
          type: integer
        x-akamai:
          file-path: parameters/page-size.yaml
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                - id: 123
                  label: linode123
                  ssh:
                    access: true
                    ip: 203.0.113.1
                    port: 22
                    user: jkowalski
                page: 1
                pages: 1
                results: 1
              schema:
                additionalProperties: false
                properties:
                  data:
                    items:
                      additionalProperties: false
                      description: Settings for a specific Linode related to Managed Services. There is one ManagedLinodeSettings object for each Linode on your Account.
                      properties:
                        group:
                          deprecated: true
                          description: __Deprecated__, __Read-only__ The group of the Linode these Settings are for. This is for display purposes only.
                          example: linodes
                          readOnly: true
                          type: string
                          x-akamai:
                            status: DEPRECATED
                          x-linode-cli-display: 3
                        id:
                          description: __Read-only__ The ID of the Linode these Settings are for.
                          example: 123
                          readOnly: true
                          type: integer
                          x-linode-cli-display: 1
                        label:
                          description: __Read-only__ The label of the Linode these Settings are for.
                          example: linode123
                          readOnly: true
                          type: string
                          x-linode-cli-display: 2
                        ssh:
                          additionalProperties: false
                          description: The SSH settings for this Linode.
                          properties:
                            access:
                              default: true
                              description: If `true`, Linode special forces may access this Linode over ssh to respond to Issues.
                              example: true
                              type: boolean
                            ip:
                              default: any
                              description: 'The IP Linode special forces should use to access this Linode when responding to an Issue.


                                By default, any of a Linode''s IP addresses can be used for incident response access.'
                              example: 203.0.113.1
                              format: ip
                              type: string
                            port:
                              default: null
                              description: 'The port Linode special forces should use to access this Linode over ssh to respond to an Issue.


                                The default `null` value corresponds to port 22.'
                              example: 22
                              maximum: 65535
                              minimum: 1
                              type:
                              - integer
                              - 'null'
                            user:
                              default: null
                              description: 'The specific user, if any, Linode''s special forces should use when accessing this Linode to respond to an issue.


                                The default `null` value corresponds to the root user.'
                              example: linode
                              maxLength: 32
                              minLength: 0
                              type:
                              - string
                              - 'null'
                          type: object
                          x-linode-cli-display: 4
                      type: object
                      x-akamai:
                        file-path: schemas/managed-linode-settings.yaml
                    type: array
                  page:
                    description: __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
                    example: 1
                    readOnly: true
                    type: integer
                  pages:
                    description: __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
                    example: 1
                    readOnly: true
                    type: integer
                  results:
                    description: __Read-only__ The total number of results.
                    example: 1
                    readOnly: true
                    type: integer
                type: object
                x-akamai:
                  file-path: schemas/get-managed-linode-settings-200.yaml
          description: A paginated list of Managed settings for your Linodes.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_only
      summary: List managed Linode settings
      tags:
      - Managed Linode settings
      x-akamai:
        tabs:
        - syntax: linode-cli managed linode-settings-list
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
        - syntax: account:read_only
          title: OAuth scopes
          url: https://techdocs.akamai.com/linode-api/reference/get-started#oauth
      x-linode-cli-action: linode-settings-list
      x-linode-grant: unrestricted only
  /{apiVersion}/managed/linode-settings/{linodeId}:
    parameters:
    - description: __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
      example: '{{apiVersion}}'
      in: path
      name: apiVersion
      required: true
      schema:
        enum:
        - v4
        - v4beta
        example: v4
        type: string
      x-akamai:
        file-path: parameters/api-version-path.yaml
    - description: The Linode ID whose settings we are accessing.
      example: '{{linodeId}}'
      in: path
      name: linodeId
      required: true
      schema:
        example: 234
        type: integer
      x-akamai:
        file-path: parameters/linode-id-path-56000749.yaml
    x-akamai:
      file-path: paths/managed-linode-settings-per-linode.yaml
      path-info: /{apiVersion}/managed/linode-settings/{linodeId}
    x-linode-cli-command: managed
    get:
      description: 'Returns the managed settings for a single Linode.


        This operation can only be accessed by the unrestricted users of an account.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_only`


        **CLI**


        ```shell

        linode-cli managed linode-setting-view 123

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/get-managed-linode-setting
      operationId: get-managed-linode-setting
      responses:
        '200':
          content:
            application/json:
              example:
                id: 123
                label: linode123
                ssh:
                  access: true
                  ip: 203.0.113.1
                  port: 22
                  user: hgildong
              schema:
                additionalProperties: false
                description: Settings for a specific Linode related to Managed Services. There is one ManagedLinodeSettings object for each Linode on your Account.
                properties:
                  group:
                    deprecated: true
                    description: __Deprecated__, __Read-only__ The group of the Linode these Settings are for. This is for display purposes only.
                    example: linodes
                    readOnly: true
                    type: string
                    x-akamai:
                      status: DEPRECATED
                    x-linode-cli-display: 3
                  id:
                    description: __Read-only__ The ID of the Linode these Settings are for.
                    example: 123
                    readOnly: true
                    type: integer
                    x-linode-cli-display: 1
                  label:
                    description: __Read-only__ The label of the Linode these Settings are for.
                    example: linode123
                    readOnly: true
                    type: string
                    x-linode-cli-display: 2
                  ssh:
                    additionalProperties: false
                    description: The SSH settings for this Linode.
                    properties:
                      access:
                        default: true
                        description: If `true`, Linode special forces may access this Linode over ssh to respond to Issues.
                        example: true
                        type: boolean
                      ip:
                        default: any
                        description: 'The IP Linode special forces should use to access this Linode when responding to an Issue.


                          By default, any of a Linode''s IP addresses can be used for incident response access.'
                        example: 203.0.113.1
                        format: ip
                        type: string
                      port:
                        default: null
                        description: 'The port Linode special forces should use to access this Linode over ssh to respond to an Issue.


                          The default `null` value corresponds to port 22.'
                        example: 22
                        maximum: 65535
                        minimum: 1
                        type:
                        - integer
                        - 'null'
                      user:
                        default: null
                        description: 'The specific user, if any, Linode''s special forces should use when accessing this Linode to respond to an issue.


                          The default `null` value corresponds to the root user.'
                        example: linode
                        maxLength: 32
                        minLength: 0
                        type:
                        - string
                        - 'null'
                    type: object
                    x-linode-cli-display: 4
                type: object
                x-akamai:
                  file-path: schemas/managed-linode-settings.yaml
          description: The requested Linode's Managed settings.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_only
      summary: Get a Linode's managed settings
      tags:
      - Managed Linode settings
      x-akamai:
        tabs:
        - syntax: linode-cli managed linode-setting-view 123
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
        - syntax: account:read_only
          title: OAuth scopes
          url: https://techdocs.akamai.com/linode-api/reference/get-started#oauth
      x-linode-cli-action: linode-setting-view
      x-linode-grant: unrestricted only
    put:
      description: 'Updates the managed settings for a Linode.


        This operation can only be accessed by the unrestricted users of an account.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_write`


        **CLI**


        ```shell

        linode-cli managed linode-setting-update \

        7833234 \

        --ssh.access true \

        --ssh.user linode \

        --ssh.port 22 \

        --ssh.ip 203.0.113.1

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/put-managed-linode-setting
      operationId: put-managed-linode-setting
      requestBody:
        content:
          application/json:
            example:
              ssh:
                access: true
                ip: 203.0.113.1
                port: 22
                user: adevi
            schema:
              additionalProperties: false
              description: Settings for a specific Linode related to Managed Services. There is one ManagedLinodeSettings object for each Linode on your Account.
              properties:
                group:
                  deprecated: true
                  description: __Deprecated__, __Read-only__ The group of the Linode these Settings are for. This is for display purposes only.
                  example: '{{group}}'
                  readOnly: true
                  type: string
                  x-akamai:
                    status: DEPRECATED
                  x-linode-cli-display: 3
                id:
                  description: __Read-only__ The ID of the Linode these Settings are for.
                  example: '{{id}}'
                  readOnly: true
                  type: integer
                  x-linode-cli-display: 1
                label:
                  description: __Read-only__ The label of the Linode these Settings are for.
                  example: '{{label}}'
                  readOnly: true
                  type: string
                  x-linode-cli-display: 2
                ssh:
                  additionalProperties: false
                  description: The SSH settings for this Linode.
                  properties:
                    access:
                      default: true
                      description: If `true`, Linode special forces may access this Linode over ssh to respond to Issues.
                      example: true
                      type: boolean
                    ip:
                      default: any
                      description: 'The IP Linode special forces should use to access this Linode when responding to an Issue.


                        By default, any of a Linode''s IP addresses can be used for incident response access.'
                      example: 203.0.113.1
                      format: ip
                      type: string
                    port:
                      default: null
                      description: 'The port Linode special forces should use to access this Linode over ssh to respond to an Issue.


                        The default `null` value corresponds to port 22.'
                      example: 22
                      maximum: 65535
                      minimum: 1
                      type:
                      - integer
                      - 'null'
                    user:
                      default: null
                      description: 'The specific user, if any, Linode''s special forces should use when accessing this Linode to respond to an issue.


                        The default `null` value corresponds to the root user.'
                      example: linode
                      maxLength: 32
                      minLength: 0
                      type:
                      - string
                      - 'null'
                  type: object
                  x-linode-cli-display: 4
              type: object
              x-akamai:
                file-path: schemas/managed-linode-settings.yaml
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                id: 123
                label: linode123
                ssh:
                  access: true
                  ip: 203.0.113.1
                  port: 22
                  user: hgildong
              schema:
                additionalProperties: false
                description: Settings for a specific Linode related to Managed Services. There is one ManagedLinodeSettings object for each Linode on your Account.
                properties:
                  group:
                    deprecated: true
                    description: __Deprecated__, __Read-only__ The group of the Linode these Settings are for. This is for display purposes only.
                    example: linodes
                    readOnly: true
                    type: string
                    x-akamai:
                      status: DEPRECATED
                    x-linode-cli-display: 3
                  id:
                    description: __Read-only__ The ID of the Linode these Settings are for.
                    example: 123
                    readOnly: true
                    type: integer
                    x-linode-cli-display: 1
                  label:
                    description: __Read-only__ The label of the Linode these Settings are for.
                    example: linode123
                    readOnly: true
                    type: string
                    x-linode-cli-display: 2
                  ssh:
                    additionalProperties: false
                    description: The SSH settings for this Linode.
                    properties:
                      access:
                        default: true
                        description: If `true`, Linode special forces may access this Linode over ssh to respond to Issues.
                        example: true
                        type: boolean
                      ip:
                        default: any
                        description: 'The IP Linode special forces should use to access this Linode when responding to an Issue.


                          By default, any of a Linode''s IP addresses can be used for incident response access.'
                        example: 203.0.113.1
                        format: ip
                        type: string
                      port:
                        default: null
                        description: 'The port Linode special forces should use to access this Linode over ssh to respond to an Issue.


                          The default `null` value corresponds to port 22.'
                        example: 22
                        maximum: 65535
                        minimum: 1
                        type:
                        - integer
                        - 'null'
                      user:
                        default: null
                        description: 'The specific user, if any, Linode''s special forces should use when accessing this Linode to respond to an issue.


                          The default `null` value corresponds to the root user.'
                        example: linode
                        maxLength: 32
                        minLength: 0
                        type:
                        - string
                        - 'null'
                    type: object
                    x-linode-cli-display: 4
                type: object
                x-akamai:
                  file-path: schemas/managed-linode-settings.yaml
          description: Settings updated successfully.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_write
      summary: Update a Linode's managed settings
      tags:
      - Managed Linode settings
      x-akamai:
        tabs:
        - syntax: "linode-cli managed linode-setting-update \\\n  7833234 \\\n  --ssh.access true \\\n  --ssh.user linode \\\n  --ssh.port 22 \\\n  --ssh.ip 203.0.113.1"
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
        - syntax: account:read_write
          title: OAuth scopes
          url: https://techdocs.akamai.com/linode-api/reference/get-started#oauth
      x-linode-cli-action: linode-setting-update
      x-linode-grant: unrestricted only
components:
  securitySchemes:
    oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://login.linode.com/oauth/authorize
          scopes:
            account:read_only: Allows access to GET information about your account.
            account:read_write: Allows access to all endpoints related to your account.
            child_account:read_only: Allows access to GET information about deprecated parent/child operations.
            child_account:read_write: Allows access to deprecated parent/child operations.
            databases:read_only: Allows access to GET information about databases.
            databases:read_write: Allows access to all endpoints related to databases.
            domains:read_only: Allows access to GET Domains on your account.
            domains:read_write: Allows access to all Domain endpoints.
            events:read_only: Allows access to GET your Events.
            events:read_write: Allows access to all endpoints related to your Events.
            firewall:read_only: Allows access to GET information about your Firewalls.
            firewall:read_write: Allows access to all Firewall endpoints.
            images:read_only: Allows access to GET your Images.
            images:read_write: Allows access to all endpoints related to your Images.
            ips:read_only: Allows access to GET your ips.
            ips:read_write: Allows access to all endpoints related to your ips.
            linodes:read_only: Allows access to GET Linodes on your account.
            linodes:read_write: Allow access to all endpoints related to your Linodes.
            lke:read_only: Allows access to GET LKE Clusters on your account.
            lke:read_write: Allows access to all endpoints related to LKE Clusters on your account.
            longview:read_only: Allows access to GET your Longview Clients.
            longview:read_write: Allows access to all endpoints related to your Longview Clients.
            monitor:read_only: Allows access to Monitor (Akamai Cloud Pulse) data.
            monitor:read_write: Allows access to GET Monitor (Akamai Cloud Pulse) data.
            nodebalancers:read_only: Allows access to GET NodeBalancers on your account.
            nodebalancers:read_write: Allows access to all NodeBalancer endpoints.
            object_storage:read_only: Allows access to GET information related to your Object Storage.
            object_storage:read_write: Allows access to all Object Storage endpoints.
            stackscripts:read_only: Allows access to GET your StackScripts.
            stackscripts:read_write: Allows access to all endpoints related to your StackScripts.
            volumes:read_only: Allows access to GET your Volumes.
            volumes:read_write: Allows access to all endpoints related to your Volumes.
            vpc:read_write: Allows access to all endpoints related to VPC and Subnet creation, updating, and deletion.
          tokenUrl: https://login.linode.com/oauth/token
      type: oauth2
    personalAccessToken:
      scheme: bearer
      type: http
externalDocs:
  description: See documentation for Akamai's Linode API
  url: https://techdocs.akamai.com/linode-api/reference
x-readme:
  explorer-enabled: false
  samples-languages:
  - curl
  - python
  - node
