openapi: 3.2.0
info:
  description: Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: 'Akamai: Linode Firewall settings API'
  version: 4.229.1
servers:
- url: https://api.linode.com
tags:
- name: Firewall settings
paths:
  /{apiVersion}/networking/firewalls/settings:
    parameters:
    - description: __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
      example: '{{apiVersion}}'
      in: path
      name: apiVersion
      required: true
      schema:
        enum:
        - v4
        - v4beta
        example: v4
        type: string
      x-akamai:
        file-path: parameters/api-version-path.yaml
    x-akamai:
      file-path: paths/firewall-settings.yaml
      path-info: /{apiVersion}/networking/firewalls/settings
    x-linode-cli-command: firewalls
    get:
      description: 'Returns default firewalls for Linodes, Linode VPC and public interfaces, and NodeBalancers.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **Identity and access permissions**. Your user needs a role with these permissions assigned. Learn more.

        - Permissions: `list_default_firewalls`

        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `firewall:read_only`


        **CLI**


        ```shell

        linode-cli firewalls firewall-settings-list

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/get-firewall-settings
      operationId: get-firewall-settings
      parameters:
      - description: The page of a collection to return.
        example: '{{page}}'
        in: query
        name: page
        required: false
        schema:
          default: 1
          example: 6
          minimum: 1
          type: integer
        x-akamai:
          file-path: parameters/page-offset.yaml
      - description: The number of items to return per page.
        example: '{{page_size}}'
        in: query
        name: page_size
        schema:
          default: 100
          example: 50
          maximum: 500
          minimum: 25
          type: integer
        x-akamai:
          file-path: parameters/page-size.yaml
      responses:
        '200':
          content:
            application/json:
              example:
                default_firewall_ids:
                  linode: 100
                  nodebalancer: 101
                  public_interface: 200
                  vpc_interface: 200
              schema:
                additionalProperties: false
                description: Default firewalls.
                properties:
                  default_firewall_ids:
                    additionalProperties: false
                    description: The default firewall ID for a `linode`, `nodebalancer`, `public_interface`, or `vpc_interface`. Default firewalls can't be deleted or disabled.
                    properties:
                      linode:
                        description: The Linode's default firewall.
                        example: 100
                        type: integer
                        x-linode-cli-display: 1
                      nodebalancer:
                        description: The NodeBalancer's default firewall.
                        example: 101
                        type: integer
                        x-linode-cli-display: 2
                      public_interface:
                        description: The public interface's default firewall.
                        example: 200
                        type: integer
                        x-linode-cli-display: 3
                      vpc_interface:
                        description: The VPC interface's default firewall.
                        example: 200
                        type: integer
                        x-linode-cli-display: 4
                    type: object
                type: object
                x-akamai:
                  file-path: schemas/firewall-settings.yaml
          description: Returns default firewalls.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - firewall:read_only
      summary: List default firewalls
      tags:
      - Firewall settings
      x-akamai:
        tabs:
        - syntax: linode-cli firewalls firewall-settings-list
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: firewall-settings-list
      x-linode-grant: read_only
      x-linode-iam:
      - permissions:
        - list_default_firewalls
    put:
      description: 'You can update or add a default firewall to:


        - Linodes using legacy config profile interfaces


        - Linode VPC interfaces and Linode public interfaces


        - NodeBalancers


        If a firewall isn''t provided during service creation, a default firewall is assigned, unless you have opted out of firewall protection.


        > 📘

        >

        > Default firewalls on Linodes with Linode interfaces are applied to the interfaces, not the Linode itself.

        >

        > Default firewalls on Linodes with legacy configuration profile interfaces are applied directly to the Linode, not its interfaces.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **Identity and access permissions**. Your user needs a role with these permissions assigned. Learn more.

        - Permissions: `update_default_firewalls`

        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_write`


        **CLI**


        ```shell

        linode-cli firewalls firewall-settings-update \

        --default_firewall_ids.vpc_interface 1 \

        --default_firewall_ids.public_interface 2 \

        --default_firewall_ids.nodebalancer 3 \

        --default_firewall_ids.linode 5

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/put-firewall-settings
      operationId: put-firewall-settings
      requestBody:
        content:
          application/json:
            example:
              default_firewall_ids:
                linode: 100
                nodebalancer: 101
                public_interface: 200
                vpc_interface: 200
            schema:
              additionalProperties: false
              description: Default firewalls.
              properties:
                default_firewall_ids:
                  additionalProperties: false
                  description: The default firewall ID for a `linode`, `nodebalancer`, `public_interface`, or `vpc_interface`. Default firewalls can't be deleted or disabled.
                  properties:
                    linode:
                      description: The Linode's default firewall.
                      example: 100
                      type: integer
                      x-linode-cli-display: 1
                    nodebalancer:
                      description: The NodeBalancer's default firewall.
                      example: 101
                      type: integer
                      x-linode-cli-display: 2
                    public_interface:
                      description: The public interface's default firewall.
                      example: 200
                      type: integer
                      x-linode-cli-display: 3
                    vpc_interface:
                      description: The VPC interface's default firewall.
                      example: 200
                      type: integer
                      x-linode-cli-display: 4
                  type: object
              type: object
              x-akamai:
                file-path: schemas/firewall-settings.yaml
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                default_firewall_ids:
                  linode: 100
                  nodebalancer: 101
                  public_interface: 200
                  vpc_interface: 200
              schema:
                additionalProperties: false
                description: Default firewalls.
                properties:
                  default_firewall_ids:
                    additionalProperties: false
                    description: The default firewall ID for a `linode`, `nodebalancer`, `public_interface`, or `vpc_interface`. Default firewalls can't be deleted or disabled.
                    properties:
                      linode:
                        description: The Linode's default firewall.
                        example: 100
                        type: integer
                        x-linode-cli-display: 1
                      nodebalancer:
                        description: The NodeBalancer's default firewall.
                        example: 101
                        type: integer
                        x-linode-cli-display: 2
                      public_interface:
                        description: The public interface's default firewall.
                        example: 200
                        type: integer
                        x-linode-cli-display: 3
                      vpc_interface:
                        description: The VPC interface's default firewall.
                        example: 200
                        type: integer
                        x-linode-cli-display: 4
                    type: object
                type: object
                x-akamai:
                  file-path: schemas/firewall-settings.yaml
          description: The updated default firewalls.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_write
      summary: Update default firewalls
      tags:
      - Firewall settings
      x-akamai:
        tabs:
        - syntax: "linode-cli firewalls firewall-settings-update \\\n  --default_firewall_ids.vpc_interface 1 \\\n  --default_firewall_ids.public_interface 2 \\\n  --default_firewall_ids.nodebalancer 3 \\\n  --default_firewall_ids.linode 5"
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: firewall-settings-update
      x-linode-grant: read_write
      x-linode-iam:
      - permissions:
        - update_default_firewalls
components:
  securitySchemes:
    oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://login.linode.com/oauth/authorize
          scopes:
            account:read_only: Allows access to GET information about your account.
            account:read_write: Allows access to all endpoints related to your account.
            child_account:read_only: Allows access to GET information about deprecated parent/child operations.
            child_account:read_write: Allows access to deprecated parent/child operations.
            databases:read_only: Allows access to GET information about databases.
            databases:read_write: Allows access to all endpoints related to databases.
            domains:read_only: Allows access to GET Domains on your account.
            domains:read_write: Allows access to all Domain endpoints.
            events:read_only: Allows access to GET your Events.
            events:read_write: Allows access to all endpoints related to your Events.
            firewall:read_only: Allows access to GET information about your Firewalls.
            firewall:read_write: Allows access to all Firewall endpoints.
            images:read_only: Allows access to GET your Images.
            images:read_write: Allows access to all endpoints related to your Images.
            ips:read_only: Allows access to GET your ips.
            ips:read_write: Allows access to all endpoints related to your ips.
            linodes:read_only: Allows access to GET Linodes on your account.
            linodes:read_write: Allow access to all endpoints related to your Linodes.
            lke:read_only: Allows access to GET LKE Clusters on your account.
            lke:read_write: Allows access to all endpoints related to LKE Clusters on your account.
            longview:read_only: Allows access to GET your Longview Clients.
            longview:read_write: Allows access to all endpoints related to your Longview Clients.
            monitor:read_only: Allows access to Monitor (Akamai Cloud Pulse) data.
            monitor:read_write: Allows access to GET Monitor (Akamai Cloud Pulse) data.
            nodebalancers:read_only: Allows access to GET NodeBalancers on your account.
            nodebalancers:read_write: Allows access to all NodeBalancer endpoints.
            object_storage:read_only: Allows access to GET information related to your Object Storage.
            object_storage:read_write: Allows access to all Object Storage endpoints.
            stackscripts:read_only: Allows access to GET your StackScripts.
            stackscripts:read_write: Allows access to all endpoints related to your StackScripts.
            volumes:read_only: Allows access to GET your Volumes.
            volumes:read_write: Allows access to all endpoints related to your Volumes.
            vpc:read_write: Allows access to all endpoints related to VPC and Subnet creation, updating, and deletion.
          tokenUrl: https://login.linode.com/oauth/token
      type: oauth2
    personalAccessToken:
      scheme: bearer
      type: http
externalDocs:
  description: See documentation for Akamai's Linode API
  url: https://techdocs.akamai.com/linode-api/reference
x-readme:
  explorer-enabled: false
  samples-languages:
  - curl
  - python
  - node
