openapi: 3.2.0
info:
  description: Add a Cloud Computing instance so you can build, release, and scale applications faster with virtual machines.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: 'Akamai: Linode Account settings API'
  version: 4.229.1
servers:
- url: https://api.linode.com
tags:
- description: Account settings applies to various services available on your account, including Backups, Linode Interfaces, a Longview subscription, Maintenance Policy, our Managed service, Network Helper, and Object Storage. Use these operations to review the services available and update some of them on your account. Talk to your Akamai account team for full details.
  name: Account settings
paths:
  /{apiVersion}/account/settings:
    parameters:
    - description: __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
      example: '{{apiVersion}}'
      in: path
      name: apiVersion
      required: true
      schema:
        enum:
        - v4
        - v4beta
        example: v4
        type: string
      x-akamai:
        file-path: parameters/api-version-path.yaml
    x-akamai:
      file-path: paths/settings.yaml
      path-info: /{apiVersion}/account/settings
    x-linode-cli-command: account
    get:
      description: 'Returns information related to your Account settings: Managed service subscription, interface settings for new Linodes, Longview subscription, and Network Helper.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **Identity and access permissions**. Your user needs a role with these permissions assigned. Learn more.

        - Permissions: `view_account_settings`

        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_only`


        **CLI**


        ```shell

        linode-cli account settings

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/get-account-settings
      operationId: get-account-settings
      responses:
        '200':
          content:
            application/json:
              example:
                backups_enabled: true
                interfaces_for_new_linodes: linode_only
                longview_subscription: longview-3
                maintenance_policy: linode/migrate
                managed: true
                network_helper: false
                object_storage: active
                tfa_enforced: true
              schema:
                additionalProperties: false
                description: Account Settings object.
                properties:
                  backups_enabled:
                    description: Account-wide backups default.  If `true`, all Linodes created will automatically be enrolled in the Backups service.  If `false`, Linodes will not be enrolled by default, but may still be enrolled on creation or later.
                    example: true
                    type: boolean
                    x-linode-cli-display: 4
                  interfaces_for_new_linodes:
                    description: 'Defines if new Linodes can use legacy configuration interfaces:

                      - `legacy_config_only`. All new Linodes need to use legacy configuration interfaces. Previously created Linodes with Linode Interfaces can still exist. Linodes using legacy configuration interfaces can''t be upgraded to use Linode Interfaces.

                      - `legacy_config_default_but_linode_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use legacy configuration interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode Interfaces. This is the default setting for existing accounts.

                      - `linode_default_but_legacy_config_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use Linode Interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode interfaces. This is the default setting for new accounts.

                      - `linode_only`. All new Linodes need to use Linode Interfaces. Previously created Linodes with legacy configuration profile interfaces can still exist if they were created under a previous setting. Linodes using legacy configuration interfaces can be upgraded to Linode Interfaces.'
                    enum:
                    - legacy_config_only
                    - legacy_config_default_but_linode_allowed
                    - linode_default_but_legacy_config_allowed
                    - linode_only
                    example: linode_only
                    type: string
                    x-linode-cli-display: 6
                  longview_subscription:
                    description: __Read-only__ The Longview Pro tier you are currently subscribed to. The value must be a [Longview subscription](https://techdocs.akamai.com/linode-api/reference/get-longview-subscriptions) ID or `null` for Longview Free.
                    example: longview-3
                    readOnly: true
                    type:
                    - string
                    - 'null'
                    x-linode-cli-display: 2
                  maintenance_policy:
                    description: Defines the default maintenance policy for new Linodes created on this account. Review [maintenance policy](https://techdocs.akamai.com/cloud-computing/docs/host-maintenance-policy) documentation for more details.
                    enum:
                    - linode/migrate
                    - linode/power_off_on
                    example: linode/migrate
                    type: string
                    x-linode-cli-display: 7
                  managed:
                    description: __Read-only__ Our 24/7 incident response service. This robust, multi-homed monitoring system distributes monitoring checks to ensure that your servers remain online and available at all times. Linode Managed can monitor any service or software stack reachable over TCP or HTTP. Once you add a service to Linode Managed, we'll monitor it for connectivity, response, and total request time.
                    example: true
                    readOnly: true
                    type: boolean
                    x-linode-cli-display: 3
                  network_helper:
                    description: Enables network helper across all users by default for new Linodes and Linode Configs.
                    example: false
                    type: boolean
                    x-linode-cli-display: 1
                  object_storage:
                    default: disabled
                    description: __Read-only__ The status of this account's Object Storage service enrollment, either `active`, `disabled`, `suspended`. If the status is `suspended`, contact Support for more information.
                    enum:
                    - disabled
                    - suspended
                    - active
                    example: active
                    readOnly: true
                    type: string
                    x-linode-cli-display: 5
                  tfa_enforced:
                    description: When `true`, all users on the account must log in with two-factor authentication (2FA), except those exempted in [List 2FA optional users](https://techdocs.akamai.com/linode-api/reference/get-account-tfa-optional-users). When `false`, 2FA is optional for all users. Defaults to `false`.
                    example: true
                    type: boolean
                    x-linode-cli-display: 8
                type: object
                x-akamai:
                  file-path: schemas/account-settings.yaml
          description: Returns a single Account settings object.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_only
      summary: Get account settings
      tags:
      - Account settings
      x-akamai:
        tabs:
        - syntax: linode-cli account settings
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: settings
      x-linode-grant: read_only
      x-linode-iam:
      - permissions:
        - view_account_settings
    put:
      description: 'Updates your account settings. For a Longview subscription plan, see Update a Longview plan.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **Identity and access permissions**. Your user needs a role with these permissions assigned. Learn more.

        - Permissions: `update_account_settings`

        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_write`


        **CLI**


        ```shell

        linode-cli account settings-update \

        --network_helper false

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/put-account-settings
      operationId: put-account-settings
      requestBody:
        content:
          application/json:
            example:
              backups_enabled: true
              interfaces_for_new_linodes: linode_only
              longview_subscription: longview-3
              maintenance_policy: linode/migrate
              managed: true
              network_helper: false
              object_storage: active
              tfa_enforced: true
            schema:
              additionalProperties: false
              description: Account Settings object.
              properties:
                backups_enabled:
                  description: Account-wide backups default.  If `true`, all Linodes created will automatically be enrolled in the Backups service.  If `false`, Linodes will not be enrolled by default, but may still be enrolled on creation or later.
                  example: '{{backups_enabled}}'
                  type: boolean
                  x-linode-cli-display: 4
                interfaces_for_new_linodes:
                  description: 'Defines if new Linodes can use legacy configuration interfaces:

                    - `legacy_config_only`. All new Linodes need to use legacy configuration interfaces. Previously created Linodes with Linode Interfaces can still exist. Linodes using legacy configuration interfaces can''t be upgraded to use Linode Interfaces.

                    - `legacy_config_default_but_linode_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use legacy configuration interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode Interfaces. This is the default setting for existing accounts.

                    - `linode_default_but_legacy_config_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use Linode Interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode interfaces. This is the default setting for new accounts.

                    - `linode_only`. All new Linodes need to use Linode Interfaces. Previously created Linodes with legacy configuration profile interfaces can still exist if they were created under a previous setting. Linodes using legacy configuration interfaces can be upgraded to Linode Interfaces.'
                  enum:
                  - legacy_config_only
                  - legacy_config_default_but_linode_allowed
                  - linode_default_but_legacy_config_allowed
                  - linode_only
                  example: '{{interfaces_for_new_linodes}}'
                  type: string
                  x-linode-cli-display: 6
                longview_subscription:
                  description: __Read-only__ The Longview Pro tier you are currently subscribed to. The value must be a [Longview subscription](https://techdocs.akamai.com/linode-api/reference/get-longview-subscriptions) ID or `null` for Longview Free.
                  example: '{{longview_subscription}}'
                  readOnly: true
                  type:
                  - string
                  - 'null'
                  x-linode-cli-display: 2
                maintenance_policy:
                  description: Defines the default maintenance policy for new Linodes created on this account. Review [maintenance policy](https://techdocs.akamai.com/cloud-computing/docs/host-maintenance-policy) documentation for more details.
                  enum:
                  - linode/migrate
                  - linode/power_off_on
                  example: '{{maintenance_policy}}'
                  type: string
                  x-linode-cli-display: 7
                managed:
                  description: __Read-only__ Our 24/7 incident response service. This robust, multi-homed monitoring system distributes monitoring checks to ensure that your servers remain online and available at all times. Linode Managed can monitor any service or software stack reachable over TCP or HTTP. Once you add a service to Linode Managed, we'll monitor it for connectivity, response, and total request time.
                  example: '{{managed}}'
                  readOnly: true
                  type: boolean
                  x-linode-cli-display: 3
                network_helper:
                  description: Enables network helper across all users by default for new Linodes and Linode Configs.
                  example: '{{network_helper}}'
                  type: boolean
                  x-linode-cli-display: 1
                object_storage:
                  default: disabled
                  description: __Read-only__ The status of this account's Object Storage service enrollment, either `active`, `disabled`, `suspended`. If the status is `suspended`, contact Support for more information.
                  enum:
                  - disabled
                  - suspended
                  - active
                  example: '{{object_storage}}'
                  readOnly: true
                  type: string
                  x-linode-cli-display: 5
                tfa_enforced:
                  description: When `true`, all users on the account must log in with two-factor authentication (2FA), except those exempted in [List 2FA optional users](https://techdocs.akamai.com/linode-api/reference/get-account-tfa-optional-users). When `false`, 2FA is optional for all users. Defaults to `false`.
                  example: '{{tfa_enforced}}'
                  type: boolean
                  x-linode-cli-display: 8
              type: object
              x-akamai:
                file-path: schemas/account-settings.yaml
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                backups_enabled: true
                interfaces_for_new_linodes: linode_only
                longview_subscription: longview-3
                maintenance_policy: linode/migrate
                managed: true
                network_helper: false
                object_storage: active
                tfa_enforced: true
              schema:
                additionalProperties: false
                description: Account Settings object.
                properties:
                  backups_enabled:
                    description: Account-wide backups default.  If `true`, all Linodes created will automatically be enrolled in the Backups service.  If `false`, Linodes will not be enrolled by default, but may still be enrolled on creation or later.
                    example: true
                    type: boolean
                    x-linode-cli-display: 4
                  interfaces_for_new_linodes:
                    description: 'Defines if new Linodes can use legacy configuration interfaces:

                      - `legacy_config_only`. All new Linodes need to use legacy configuration interfaces. Previously created Linodes with Linode Interfaces can still exist. Linodes using legacy configuration interfaces can''t be upgraded to use Linode Interfaces.

                      - `legacy_config_default_but_linode_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use legacy configuration interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode Interfaces. This is the default setting for existing accounts.

                      - `linode_default_but_legacy_config_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use Linode Interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode interfaces. This is the default setting for new accounts.

                      - `linode_only`. All new Linodes need to use Linode Interfaces. Previously created Linodes with legacy configuration profile interfaces can still exist if they were created under a previous setting. Linodes using legacy configuration interfaces can be upgraded to Linode Interfaces.'
                    enum:
                    - legacy_config_only
                    - legacy_config_default_but_linode_allowed
                    - linode_default_but_legacy_config_allowed
                    - linode_only
                    example: linode_only
                    type: string
                    x-linode-cli-display: 6
                  longview_subscription:
                    description: __Read-only__ The Longview Pro tier you are currently subscribed to. The value must be a [Longview subscription](https://techdocs.akamai.com/linode-api/reference/get-longview-subscriptions) ID or `null` for Longview Free.
                    example: longview-3
                    readOnly: true
                    type:
                    - string
                    - 'null'
                    x-linode-cli-display: 2
                  maintenance_policy:
                    description: Defines the default maintenance policy for new Linodes created on this account. Review [maintenance policy](https://techdocs.akamai.com/cloud-computing/docs/host-maintenance-policy) documentation for more details.
                    enum:
                    - linode/migrate
                    - linode/power_off_on
                    example: linode/migrate
                    type: string
                    x-linode-cli-display: 7
                  managed:
                    description: __Read-only__ Our 24/7 incident response service. This robust, multi-homed monitoring system distributes monitoring checks to ensure that your servers remain online and available at all times. Linode Managed can monitor any service or software stack reachable over TCP or HTTP. Once you add a service to Linode Managed, we'll monitor it for connectivity, response, and total request time.
                    example: true
                    readOnly: true
                    type: boolean
                    x-linode-cli-display: 3
                  network_helper:
                    description: Enables network helper across all users by default for new Linodes and Linode Configs.
                    example: false
                    type: boolean
                    x-linode-cli-display: 1
                  object_storage:
                    default: disabled
                    description: __Read-only__ The status of this account's Object Storage service enrollment, either `active`, `disabled`, `suspended`. If the status is `suspended`, contact Support for more information.
                    enum:
                    - disabled
                    - suspended
                    - active
                    example: active
                    readOnly: true
                    type: string
                    x-linode-cli-display: 5
                  tfa_enforced:
                    description: When `true`, all users on the account must log in with two-factor authentication (2FA), except those exempted in [List 2FA optional users](https://techdocs.akamai.com/linode-api/reference/get-account-tfa-optional-users). When `false`, 2FA is optional for all users. Defaults to `false`.
                    example: true
                    type: boolean
                    x-linode-cli-display: 8
                type: object
                x-akamai:
                  file-path: schemas/account-settings.yaml
          description: The updated Account settings.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_write
      summary: Update account settings
      tags:
      - Account settings
      x-akamai:
        tabs:
        - syntax: "linode-cli account settings-update \\\n  --network_helper false"
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: settings-update
      x-linode-grant: read_write
      x-linode-iam:
      - permissions:
        - update_account_settings
  /{apiVersion}/account/settings/managed-enable:
    parameters:
    - description: __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
      example: '{{apiVersion}}'
      in: path
      name: apiVersion
      required: true
      schema:
        enum:
        - v4
        - v4beta
        example: v4
        type: string
      x-akamai:
        file-path: parameters/api-version-path.yaml
    x-akamai:
      file-path: paths/account-settings-managed-enable.yaml
      path-info: /{apiVersion}/account/settings/managed-enable
    x-linode-cli-command: account
    post:
      description: 'Enables Linode Managed for the entire account and sends a welcome email to the account''s associated email address. Linode Managed can monitor any service or software stack reachable over TCP or HTTP. See our Linode Managed guide to learn more.


        **Permissions and scopes**


        To call this operation, you need the following:


        - **Identity and access permissions**. Your user needs a role with these permissions assigned. Learn more.

        - Permissions: `enable_managed`

        - **OAuth scopes**. Your user needs these scopes assigned. Learn more.


        - Scopes: `account:read_write`


        **CLI**


        ```shell

        linode-cli account enable-managed

        ```


        Learn more'
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/post-enable-account-managed
      operationId: post-enable-account-managed
      responses:
        '200':
          content:
            application/json:
              example: {}
              schema:
                description: The API responds with an empty object.
                maxProperties: 0
                type: object
                x-akamai:
                  file-path: schemas/added-empty-obj.yaml
          description: Managed services enabled for account.
        default:
          content:
            application/json:
              example:
                errors:
                - reason: Invalid JSON
              schema:
                additionalProperties: false
                properties:
                  errors:
                    description: Any warnings associated with a response.
                    items:
                      additionalProperties: false
                      description: An object for describing a single error that occurred during the processing of a request.
                      properties:
                        field:
                          description: The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
      security:
      - personalAccessToken: []
      - oauth:
        - account:read_write
      summary: Enable Linode Managed
      tags:
      - Account settings
      x-akamai:
        tabs:
        - syntax: linode-cli account enable-managed
          title: CLI
          url: https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: enable-managed
      x-linode-grant: read_write
      x-linode-iam:
      - permissions:
        - enable_managed
components:
  securitySchemes:
    oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://login.linode.com/oauth/authorize
          scopes:
            account:read_only: Allows access to GET information about your account.
            account:read_write: Allows access to all endpoints related to your account.
            child_account:read_only: Allows access to GET information about deprecated parent/child operations.
            child_account:read_write: Allows access to deprecated parent/child operations.
            databases:read_only: Allows access to GET information about databases.
            databases:read_write: Allows access to all endpoints related to databases.
            domains:read_only: Allows access to GET Domains on your account.
            domains:read_write: Allows access to all Domain endpoints.
            events:read_only: Allows access to GET your Events.
            events:read_write: Allows access to all endpoints related to your Events.
            firewall:read_only: Allows access to GET information about your Firewalls.
            firewall:read_write: Allows access to all Firewall endpoints.
            images:read_only: Allows access to GET your Images.
            images:read_write: Allows access to all endpoints related to your Images.
            ips:read_only: Allows access to GET your ips.
            ips:read_write: Allows access to all endpoints related to your ips.
            linodes:read_only: Allows access to GET Linodes on your account.
            linodes:read_write: Allow access to all endpoints related to your Linodes.
            lke:read_only: Allows access to GET LKE Clusters on your account.
            lke:read_write: Allows access to all endpoints related to LKE Clusters on your account.
            longview:read_only: Allows access to GET your Longview Clients.
            longview:read_write: Allows access to all endpoints related to your Longview Clients.
            monitor:read_only: Allows access to Monitor (Akamai Cloud Pulse) data.
            monitor:read_write: Allows access to GET Monitor (Akamai Cloud Pulse) data.
            nodebalancers:read_only: Allows access to GET NodeBalancers on your account.
            nodebalancers:read_write: Allows access to all NodeBalancer endpoints.
            object_storage:read_only: Allows access to GET information related to your Object Storage.
            object_storage:read_write: Allows access to all Object Storage endpoints.
            stackscripts:read_only: Allows access to GET your StackScripts.
            stackscripts:read_write: Allows access to all endpoints related to your StackScripts.
            volumes:read_only: Allows access to GET your Volumes.
            volumes:read_write: Allows access to all endpoints related to your Volumes.
            vpc:read_write: Allows access to all endpoints related to VPC and Subnet creation, updating, and deletion.
          tokenUrl: https://login.linode.com/oauth/token
      type: oauth2
    personalAccessToken:
      scheme: bearer
      type: http
externalDocs:
  description: See documentation for Akamai's Linode API
  url: https://techdocs.akamai.com/linode-api/reference
x-readme:
  explorer-enabled: false
  samples-languages:
  - curl
  - python
  - node
